version: 3.8

services:
  request-mirror:
    image: request-mirror
    ports:
      - 80:80
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres
    networks:
      - app-network
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=request_mirror_db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24

volumes:
  db-data: