version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=request_mirror_db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d request_mirror_db | grep 'accepting connections'"]
  request-mirror:
    #image: request-mirror
    build: &request_mirror_build
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:8000
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres/request_mirror_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24

volumes:
  db-data: