[default]
address = "0.0.0.0"
port = 8000
keep_alive = 5
log_level = "normal"
limits = { forms = 32768 }

[release]
address = "0.0.0.0"
port = 80
keep_alive = 5
log_level = "critical"
limits = { forms = 32768 }

[docker]
address = "0.0.0.0"
port = 80
keep_alive = 5
log_level = "critical"
limits = { forms = 32768 }
template_dir = "/templates/"