name: Build and Test Rust

on:
  push:
    branches: [ "main", "test"]
  pull_request:
    branches: [ "main", "test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose